/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_hribar_thesis_Weekday */

#ifndef _Included_info_hribar_thesis_Weekday
#define _Included_info_hribar_thesis_Weekday
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
