/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_hribar_thesis_Recurrence */

#ifndef _Included_info_hribar_thesis_Recurrence
#define _Included_info_hribar_thesis_Recurrence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    init
 * Signature: (Linfo/hribar/thesis/Frequency;Linfo/hribar/thesis/Date;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    daysInRange
 * Signature: (Linfo/hribar/thesis/Date;Linfo/hribar/thesis/Date;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_info_hribar_thesis_Recurrence_daysInRange
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getStart
 * Signature: ()Linfo/hribar/thesis/Date;
 */
JNIEXPORT jobject JNICALL Java_info_hribar_thesis_Recurrence_getStart
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setStart
 * Signature: (Linfo/hribar/thesis/Date;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setStart
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getUntil
 * Signature: ()Linfo/hribar/thesis/Date;
 */
JNIEXPORT jobject JNICALL Java_info_hribar_thesis_Recurrence_getUntil
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setUntil
 * Signature: (Linfo/hribar/thesis/Date;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setUntil
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getFrequency
 * Signature: ()Linfo/hribar/thesis/Frequency;
 */
JNIEXPORT jobject JNICALL Java_info_hribar_thesis_Recurrence_getFrequency
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setFrequency
 * Signature: (Linfo/hribar/thesis/Frequency;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setFrequency
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_hribar_thesis_Recurrence_getInterval
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_hribar_thesis_Recurrence_getCount
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getByDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_hribar_thesis_Recurrence_getByDay
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setByDay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setByDay
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    getByMonthDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_hribar_thesis_Recurrence_getByMonthDay
  (JNIEnv *, jobject);

/*
 * Class:     info_hribar_thesis_Recurrence
 * Method:    setByMonthDay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_hribar_thesis_Recurrence_setByMonthDay
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
